import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export type Bet = {
  id: string;
  user: string;
  avatar: string;
  amount: number;
  cashedOut: number;
  x: number;
};

export const bets: Bet[] = [
  {
    id: "1",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***3",
    amount: 100,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "2",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***4",
    amount: 100,
    x: 2.45,
    cashedOut: 124,
  },
  {
    id: "3",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***5",
    amount: 150,
    x: 1.75,
    cashedOut: 0,
  },
  {
    id: "4",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***6",
    amount: 200,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "5",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***7",
    amount: 50,
    x: 1.90,
    cashedOut: 95,
  },
  {
    id: "6",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***8",
    amount: 75,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "7",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***9",
    amount: 120,
    x: 1.85,
    cashedOut: 222,
  },
  {
    id: "8",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***10",
    amount: 90,
    x: 2.30,
    cashedOut: 0,
  },
  {
    id: "9",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***11",
    amount: 110,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "10",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***12",
    amount: 130,
    x: 2.15,
    cashedOut: 279,
  },
  {
    id: "11",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***13",
    amount: 140,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "12",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***14",
    amount: 160,
    x: 1.50,
    cashedOut: 240,
  },
  {
    id: "13",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***15",
    amount: 180,
    x: 2.10,
    cashedOut: 378,
  },
  {
    id: "14",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***16",
    amount: 70,
    x: 1.95,
    cashedOut: 136.5,
  },
  {
    id: "15",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***17",
    amount: 50,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "16",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***18",
    amount: 100,
    x: 2.00,
    cashedOut: 200,
  },
  {
    id: "17",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***19",
    amount: 120,
    x: 1.80,
    cashedOut: 216,
  },
  {
    id: "18",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***20",
    amount: 90,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "19",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***21",
    amount: 85,
    x: 1.95,
    cashedOut: 165.75,
  },
  {
    id: "20",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***22",
    amount: 60,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "21",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***23",
    amount: 150,
    x: 2.25,
    cashedOut: 337.5,
  },
  {
    id: "22",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***24",
    amount: 200,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "23",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***25",
    amount: 50,
    x: 1.75,
    cashedOut: 87.5,
  },
  {
    id: "24",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***26",
    amount: 180,
    x: 2.00,
    cashedOut: 360,
  },
  {
    id: "25",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***27",
    amount: 95,
    x: 1.50,
    cashedOut: 142.5,
  },
  {
    id: "26",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***28",
    amount: 200,
    x: 1.85,
    cashedOut: 370,
  },
  {
    id: "27",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***29",
    amount: 120,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "28",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***30",
    amount: 140,
    x: 2.50,
    cashedOut: 350,
  },
  {
    id: "29",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***31",
    amount: 80,
    x: 1.65,
    cashedOut: 132,
  },
  {
    id: "30",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***32",
    amount: 60,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "31",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***33",
    amount: 100,
    x: 2.10,
    cashedOut: 210,
  },
  {
    id: "32",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***34",
    amount: 70,
    x: 0,
    cashedOut: 0,
  },
  {
    id: "33",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***35",
    amount: 130,
    x: 1.75,
    cashedOut: 227.5,
  },
  {
    id: "34",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***36",
    amount: 190,
    x: 1.95,
    cashedOut: 370.5,
  },
  {
    id: "35",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***37",
    amount: 80,
    x: 2.00,
    cashedOut: 160,
  },
  {
    id: "36",
    avatar: "/placeholder.svg?height=32&width=32",
    user: "d***38",
    amount: 110,
    x: 1.85,
    cashedOut: 203.5,
  }
];
